import { type Project } from '@/types'

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: 'App de Agendamento',
    description: 'Sistema de agendamentos para clínicas com notificações automáticas e integração com agenda do médico',
    company_id: '1',
    created_by: '1',
    created_at: '2024-03-10T10:00:00Z',
    status: 'specification',
    progress: 50,
  },
  {
    id: '2',
    name: 'Portal do Cliente',
    description: 'Portal de autoatendimento para clientes acessarem pedidos, faturas e histórico de compras',
    company_id: '1',
    created_by: '1',
    created_at: '2024-03-08T14:00:00Z',
    status: 'manual',
    progress: 90,
  },
  {
    id: '3',
    name: 'Integração ERP',
    description: 'Integração entre sistemas de gestão e plataforma de e-commerce via API REST',
    company_id: '1',
    created_by: '1',
    created_at: '2024-03-12T09:00:00Z',
    status: 'briefing',
    progress: 10,
  },
  {
    id: '4',
    name: 'Dashboard Analytics',
    description: 'Painel de métricas em tempo real para equipes de operações e gestores',
    company_id: '1',
    created_by: '1',
    created_at: '2024-03-05T11:00:00Z',
    status: 'done',
    progress: 100,
  },
  {
    id: '5',
    name: 'Módulo de RH',
    description: 'Gestão de férias, ponto eletrônico e documentos dos colaboradores',
    company_id: '1',
    created_by: '1',
    created_at: '2024-03-13T16:00:00Z',
    status: 'refinement',
    progress: 30,
  },
  {
    id: '6',
    name: 'Sistema de Notificações',
    description: 'Centralizador de notificações por e-mail, SMS e push para múltiplos canais',
    company_id: '1',
    created_by: '1',
    created_at: '2024-03-14T08:30:00Z',
    status: 'documentation',
    progress: 70,
  },
  {
    id: '7',
    name: 'App Mobile Delivery',
    description: 'Aplicativo de delivery para restaurantes com rastreamento em tempo real',
    company_id: '1',
    created_by: '1',
    created_at: '2024-03-15T10:00:00Z',
    status: 'briefing',
    progress: 10,
  },
  {
    id: '8',
    name: 'Relatórios Financeiros',
    description: 'Geração automatizada de relatórios contábeis e DRE com exportação PDF/Excel',
    company_id: '1',
    created_by: '1',
    created_at: '2024-02-28T09:00:00Z',
    status: 'done',
    progress: 100,
  },
]
